# https://hanab.live/replay/1198685
from constants.action_source import ActionSource
from services.game_builder import GameBuilder

raw_data = [{"start": {"playerNames": ["LaFayetteBot2", "LaFayetteX", "LaFayetteBot1"], "ourPlayerIndex": 2}},
            {"draw": {"playerIndex": 0, "order": 0, "rank": 1, "suitIndex": 1}},
            {"draw": {"playerIndex": 0, "order": 1, "rank": 4, "suitIndex": 0}},
            {"draw": {"playerIndex": 0, "order": 2, "rank": 2, "suitIndex": 3}},
            {"draw": {"playerIndex": 0, "order": 3, "rank": 1, "suitIndex": 0}},
            {"draw": {"playerIndex": 0, "order": 4, "rank": 2, "suitIndex": 4}},
            {"draw": {"playerIndex": 1, "order": 5, "rank": 2, "suitIndex": 0}},
            {"draw": {"playerIndex": 1, "order": 6, "rank": 1, "suitIndex": 4}},
            {"draw": {"playerIndex": 1, "order": 7, "rank": 2, "suitIndex": 1}},
            {"draw": {"playerIndex": 1, "order": 8, "rank": 4, "suitIndex": 2}},
            {"draw": {"playerIndex": 1, "order": 9, "rank": 1, "suitIndex": 3}},
            {"draw": {"playerIndex": 2, "order": 10, "rank": -1, "suitIndex": -1}},
            {"draw": {"playerIndex": 2, "order": 11, "rank": -1, "suitIndex": -1}},
            {"draw": {"playerIndex": 2, "order": 12, "rank": -1, "suitIndex": -1}},
            {"draw": {"playerIndex": 2, "order": 13, "rank": -1, "suitIndex": -1}},
            {"draw": {"playerIndex": 2, "order": 14, "rank": -1, "suitIndex": -1}}, {"game": "ready"},
            {"clue": {"player_index": 1, "is_color_clue": False, "value": 2, "card_orders_touched": [5, 7]}},
            {"turn": {"turn_number": 1, "current_player_index": 1}},
            {"clue": {"player_index": 0, "is_color_clue": False, "value": 1, "card_orders_touched": [0, 3]}},
            {"turn": {"turn_number": 2, "current_player_index": 2}},
            {"action": {"action_type": 3, "target": 1, "value": 1}},
            {"clue": {"player_index": 1, "is_color_clue": False, "value": 1, "card_orders_touched": [6, 9]}},
            {"turn": {"turn_number": 3, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 3, "rank": 1, "suitIndex": 0}},
            {"draw": {"playerIndex": 0, "order": 15, "rank": 2, "suitIndex": 1}},
            {"turn": {"turn_number": 4, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 6, "rank": 1, "suitIndex": 4}},
            {"draw": {"playerIndex": 1, "order": 16, "rank": 4, "suitIndex": 1}},
            {"turn": {"turn_number": 5, "current_player_index": 2}},
            {"action": {"action_type": 2, "target": 0, "value": 4}},
            {"clue": {"player_index": 0, "is_color_clue": True, "value": 4, "card_orders_touched": [4]}},
            {"turn": {"turn_number": 6, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 0, "rank": 1, "suitIndex": 1}},
            {"draw": {"playerIndex": 0, "order": 17, "rank": 1, "suitIndex": 1}},
            {"turn": {"turn_number": 7, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 9, "rank": 1, "suitIndex": 3}},
            {"draw": {"playerIndex": 1, "order": 18, "rank": 2, "suitIndex": 0}},
            {"turn": {"turn_number": 8, "current_player_index": 2}},
            {"action": {"action_type": 2, "target": 0, "value": 3}},
            {"clue": {"player_index": 0, "is_color_clue": True, "value": 3, "card_orders_touched": [2]}},
            {"turn": {"turn_number": 9, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 2, "rank": 2, "suitIndex": 3}},
            {"draw": {"playerIndex": 0, "order": 19, "rank": 5, "suitIndex": 1}},
            {"turn": {"turn_number": 10, "current_player_index": 1}},
            {"clue": {"player_index": 0, "is_color_clue": False, "value": 2, "card_orders_touched": [4, 15]}},
            {"turn": {"turn_number": 11, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 10, "value": None}},
            {"discard": {"playerIndex": 2, "order": 10, "rank": 4, "suitIndex": 2}},
            {"draw": {"playerIndex": 2, "order": 20, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 12, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 4, "rank": 2, "suitIndex": 4}},
            {"draw": {"playerIndex": 0, "order": 21, "rank": 5, "suitIndex": 4}},
            {"turn": {"turn_number": 13, "current_player_index": 1}},
            {"discard": {"playerIndex": 1, "order": 8, "rank": 4, "suitIndex": 2}},
            {"draw": {"playerIndex": 1, "order": 22, "rank": 3, "suitIndex": 3}},
            {"turn": {"turn_number": 14, "current_player_index": 2}},
            {"action": {"action_type": 3, "target": 1, "value": 3}},
            {"clue": {"player_index": 1, "is_color_clue": False, "value": 3, "card_orders_touched": [22]}},
            {"turn": {"turn_number": 15, "current_player_index": 0}},
            {"discard": {"playerIndex": 0, "order": 15, "rank": 2, "suitIndex": 1}},
            {"draw": {"playerIndex": 0, "order": 23, "rank": 1, "suitIndex": 2}},
            {"turn": {"turn_number": 16, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 22, "rank": 3, "suitIndex": 3}},
            {"draw": {"playerIndex": 1, "order": 24, "rank": 2, "suitIndex": 2}},
            {"turn": {"turn_number": 17, "current_player_index": 2}},
            {"action": {"action_type": 2, "target": 0, "value": 2}},
            {"clue": {"player_index": 0, "is_color_clue": True, "value": 2, "card_orders_touched": [23]}},
            {"turn": {"turn_number": 18, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 23, "rank": 1, "suitIndex": 2}},
            {"draw": {"playerIndex": 0, "order": 25, "rank": 4, "suitIndex": 0}},
            {"turn": {"turn_number": 19, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 7, "rank": 2, "suitIndex": 1}},
            {"draw": {"playerIndex": 1, "order": 26, "rank": 5, "suitIndex": 0}},
            {"turn": {"turn_number": 20, "current_player_index": 2}},
            {"action": {"action_type": 2, "target": 1, "value": 2}},
            {"clue": {"player_index": 1, "is_color_clue": True, "value": 2, "card_orders_touched": [24]}},
            {"turn": {"turn_number": 21, "current_player_index": 0}},
            {"clue": {"player_index": 2, "is_color_clue": True, "value": 1, "card_orders_touched": [14]}},
            {"turn": {"turn_number": 22, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 24, "rank": 2, "suitIndex": 2}},
            {"draw": {"playerIndex": 1, "order": 27, "rank": 1, "suitIndex": 3}},
            {"turn": {"turn_number": 23, "current_player_index": 2}},
            {"action": {"action_type": 0, "target": 14, "value": None}},
            {"play": {"playerIndex": 2, "order": 14, "rank": 3, "suitIndex": 1}},
            {"draw": {"playerIndex": 2, "order": 28, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 24, "current_player_index": 0}},
            {"clue": {"player_index": 1, "is_color_clue": True, "value": 1, "card_orders_touched": [16]}},
            {"turn": {"turn_number": 25, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 5, "rank": 2, "suitIndex": 0}},
            {"draw": {"playerIndex": 1, "order": 29, "rank": 3, "suitIndex": 4}},
            {"turn": {"turn_number": 26, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 11, "value": None}},
            {"discard": {"playerIndex": 2, "order": 11, "rank": 3, "suitIndex": 2}},
            {"draw": {"playerIndex": 2, "order": 30, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 27, "current_player_index": 0}},
            {"clue": {"player_index": 1, "is_color_clue": True, "value": 4, "card_orders_touched": [29]}},
            {"turn": {"turn_number": 28, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 16, "rank": 4, "suitIndex": 1}},
            {"draw": {"playerIndex": 1, "order": 31, "rank": 3, "suitIndex": 1}},
            {"turn": {"turn_number": 29, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 12, "value": None}},
            {"discard": {"playerIndex": 2, "order": 12, "rank": 1, "suitIndex": 0}},
            {"draw": {"playerIndex": 2, "order": 32, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 30, "current_player_index": 0}},
            {"discard": {"playerIndex": 0, "order": 1, "rank": 4, "suitIndex": 0}},
            {"draw": {"playerIndex": 0, "order": 33, "rank": 5, "suitIndex": 3}},
            {"turn": {"turn_number": 31, "current_player_index": 1}},
            {"play": {"playerIndex": 1, "order": 29, "rank": 3, "suitIndex": 4}},
            {"draw": {"playerIndex": 1, "order": 34, "rank": 2, "suitIndex": 2}},
            {"turn": {"turn_number": 32, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 13, "value": None}},
            {"discard": {"playerIndex": 2, "order": 13, "rank": 3, "suitIndex": 3}},
            {"draw": {"playerIndex": 2, "order": 35, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 33, "current_player_index": 0}},
            {"discard": {"playerIndex": 0, "order": 17, "rank": 1, "suitIndex": 1}},
            {"draw": {"playerIndex": 0, "order": 36, "rank": 4, "suitIndex": 4}},
            {"turn": {"turn_number": 34, "current_player_index": 1}},
            {"clue": {"player_index": 0, "is_color_clue": True, "value": 4, "card_orders_touched": [21, 36]}},
            {"turn": {"turn_number": 35, "current_player_index": 2}},
            {"action": {"action_type": 3, "target": 0, "value": 5}},
            {"clue": {"player_index": 0, "is_color_clue": False, "value": 5, "card_orders_touched": [19, 21, 33]}},
            {"turn": {"turn_number": 36, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 36, "rank": 4, "suitIndex": 4}},
            {"draw": {"playerIndex": 0, "order": 37, "rank": 3, "suitIndex": 0}},
            {"turn": {"turn_number": 37, "current_player_index": 1}},
            {"clue": {"player_index": 0, "is_color_clue": False, "value": 3, "card_orders_touched": [37]}},
            {"turn": {"turn_number": 38, "current_player_index": 2}},
            {"action": {"action_type": 3, "target": 0, "value": 4}},
            {"clue": {"player_index": 0, "is_color_clue": False, "value": 4, "card_orders_touched": [25]}},
            {"turn": {"turn_number": 39, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 21, "rank": 5, "suitIndex": 4}},
            {"draw": {"playerIndex": 0, "order": 38, "rank": 3, "suitIndex": 2}},
            {"turn": {"turn_number": 40, "current_player_index": 1}},
            {"clue": {"player_index": 0, "is_color_clue": True, "value": 2, "card_orders_touched": [38]}},
            {"turn": {"turn_number": 41, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 20, "value": None}},
            {"discard": {"playerIndex": 2, "order": 20, "rank": 1, "suitIndex": 3}},
            {"draw": {"playerIndex": 2, "order": 39, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 42, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 37, "rank": 3, "suitIndex": 0}},
            {"draw": {"playerIndex": 0, "order": 40, "rank": 4, "suitIndex": 3}},
            {"turn": {"turn_number": 43, "current_player_index": 1}},
            {"clue": {"player_index": 0, "is_color_clue": True, "value": 3, "card_orders_touched": [33, 40]}},
            {"turn": {"turn_number": 44, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 28, "value": None}},
            {"discard": {"playerIndex": 2, "order": 28, "rank": 3, "suitIndex": 4}},
            {"draw": {"playerIndex": 2, "order": 41, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 45, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 40, "rank": 4, "suitIndex": 3}},
            {"draw": {"playerIndex": 0, "order": 42, "rank": 5, "suitIndex": 2}},
            {"turn": {"turn_number": 46, "current_player_index": 1}},
            {"discard": {"playerIndex": 1, "order": 18, "rank": 2, "suitIndex": 0}},
            {"draw": {"playerIndex": 1, "order": 43, "rank": 4, "suitIndex": 4}},
            {"turn": {"turn_number": 47, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 35, "value": None}},
            {"discard": {"playerIndex": 2, "order": 35, "rank": 4, "suitIndex": 1}},
            {"draw": {"playerIndex": 2, "order": 44, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 48, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 25, "rank": 4, "suitIndex": 0}},
            {"draw": {"playerIndex": 0, "order": 45, "rank": 1, "suitIndex": 1}},
            {"turn": {"turn_number": 49, "current_player_index": 1}},
            {"discard": {"playerIndex": 1, "order": 26, "rank": 5, "suitIndex": 0}},
            {"draw": {"playerIndex": 1, "order": 46, "rank": 4, "suitIndex": 3}},
            {"turn": {"turn_number": 50, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 30, "value": None}},
            {"discard": {"playerIndex": 2, "order": 30, "rank": 1, "suitIndex": 2}},
            {"draw": {"playerIndex": 2, "order": 47, "rank": -1, "suitIndex": -1}},
            {"turn": {"turn_number": 51, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 19, "rank": 5, "suitIndex": 1}},
            {"draw": {"playerIndex": 0, "order": 48, "rank": 1, "suitIndex": 4}},
            {"turn": {"turn_number": 52, "current_player_index": 1}},
            {"discard": {"playerIndex": 1, "order": 27, "rank": 1, "suitIndex": 3}},
            {"draw": {"playerIndex": 1, "order": 49, "rank": 2, "suitIndex": 4}},
            {"turn": {"turn_number": 53, "current_player_index": 2}},
            {"action": {"action_type": 1, "target": 41, "value": None}},
            {"discard": {"playerIndex": 2, "order": 41, "rank": 1, "suitIndex": 2}},
            {"turn": {"turn_number": 54, "current_player_index": 0}},
            {"play": {"playerIndex": 0, "order": 38, "rank": 3, "suitIndex": 2}}]


def test_turn_48_should_give_5():
    game_builder = GameBuilder(raw_data)
    game_builder.build_until_turn(47)
    game = game_builder.export_game()
    assert game.turn_number == 47
    assert game.current_player_index == 2

    actions = game.brain.find_potential_actions()
    best_action = game.brain.choose_action(actions)
    assert best_action.source == ActionSource.SAVE_CLUE
